### ISSUE TITLE
Support Request : How can the site-superadmin allow a certain number of tabs as the maximum number

### ISSUE THREAD

**Issue by dranii** [AU-Landing-Project/mt_activity_tabs#1]
How can the site-superadmin allow a certain number of tabs as the maximum number by the end-user.

For example, an end-user who is using mobile or small screen, goes on adding some 15 or 20 tabs - it becomes congested and ugly. If there is any way the site super-admin can set the max number of tab values at  X.
Also, an admin setting to  truncate names once they are beyond x characters or some css - which comes handy in case of Unicode characters,

**Comment by beck24** [comment]
No limit is imposed, navigation should be responsive to handle tabs that exceed the container capacity
